// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhetGqWEMNT__87TXmMIMRzGUvV1YmuEc',
    appId: '1:1082351517973:web:8693b3879bc584c030a91c',
    messagingSenderId: '1082351517973',
    projectId: 'patrimonie-34d91',
    authDomain: 'patrimonie-34d91.firebaseapp.com',
    storageBucket: 'patrimonie-34d91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wDxl-hbtsR-aw7Ohui8xELbNg-A5F3w',
    appId: '1:1082351517973:android:0103f65cdc5a701830a91c',
    messagingSenderId: '1082351517973',
    projectId: 'patrimonie-34d91',
    storageBucket: 'patrimonie-34d91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCRQ4lOf1H0TiWxCZeFXC5mga4kGN-CKk',
    appId: '1:1082351517973:ios:234524d8acef9fee30a91c',
    messagingSenderId: '1082351517973',
    projectId: 'patrimonie-34d91',
    storageBucket: 'patrimonie-34d91.appspot.com',
    iosBundleId: 'com.example.patrimonie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCRQ4lOf1H0TiWxCZeFXC5mga4kGN-CKk',
    appId: '1:1082351517973:ios:234524d8acef9fee30a91c',
    messagingSenderId: '1082351517973',
    projectId: 'patrimonie-34d91',
    storageBucket: 'patrimonie-34d91.appspot.com',
    iosBundleId: 'com.example.patrimonie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhetGqWEMNT__87TXmMIMRzGUvV1YmuEc',
    appId: '1:1082351517973:web:700fe7b74e84027d30a91c',
    messagingSenderId: '1082351517973',
    projectId: 'patrimonie-34d91',
    authDomain: 'patrimonie-34d91.firebaseapp.com',
    storageBucket: 'patrimonie-34d91.appspot.com',
  );
}
